### ISSUE TITLE
Negative Colors

### ISSUE THREAD

**Issue by KiN4Tec** [carl-vbn/pure-java-raytracer#2]
It may not be a big problem but colors can be supplied by negative values or added/multiplied by negative values and there is no exception preventing an error in the program from doing that.

I don't know much java but i think it can be fixed using clamp function like:

```java
clamp(0F, red, 1F);
```

Or:

```java
clamp(1F, red, 0F);
```

I don't know how the order exactly.

Edit:

I'm talking about the Color class in the pixeldata folder.

**Comment by carl-vbn** [comment]
This could indeed be fixed quite easily but as this was just a fun testing project I made 10 months ago I don't feel like this issue needs to be addressed. Thanks for pointing it out though!
