### ISSUE TITLE
Compiler errors

### ISSUE THREAD

**Issue by Chris2918** [carl-vbn/pure-java-raytracer#3]
Hi, I would love to see this for myself, but I only got one .java file compiled. The rest had compiler errors. It seems like it will not compile with those errors. I just use the javac program/command. I heard that you cannot ignore the errors, the only way to fix this is for the guy having the files to fix the files themselves.
If you want screenshots, here.
![compilerror1](https://user-images.githubusercontent.com/37005770/109874393-0f829f00-7c3d-11eb-8eea-e6c01c142301.PNG)
![compilerror2](https://user-images.githubusercontent.com/37005770/109874573-48bb0f00-7c3d-11eb-8c2d-6cb6ce535f89.PNG)

**Comment by carl-vbn** [comment]
This isn't an issue with the code, it's just that all .java files depend on each other, so you have to compile them all at the same time. There's a javac command to do so but I would recommend using an IDE like Eclipse or IntelliJ IDEA to open and run the project

**Comment by Chris2918** [comment]
Alright, thanks. :)
