### ISSUE TITLE
how do i compile this?

### ISSUE THREAD

**Issue by speedingegg** [carl-vbn/pure-java-raytracer#6]

**Comment by carl-vbn** [comment]
This is a Java project. I recommend importing it into a Java IDE. My recommendation would be IntelliJ IDEA, as it's what I used to create it.

**Comment by speedingegg** [comment]
im not so familiar with intelliJ, and i dont know how to compile it

**Comment by carl-vbn** [comment]
If you prefer another IDE, you can use it instead. If you are not familiar with Java as a whole, I suggest looking up how to import and run a project in IntelliJ on the internet.

**Comment by speedingegg** [comment]
alright! i might need some help later tho

**Comment by speedingegg** [comment]
alright, it just wont compile, do you have a compiled one? im desperate

**Comment by carl-vbn** [comment]
There is a release available ([link here](https://github.com/carl-vbn/pure-java-raytracer/releases/tag/1.0)), but it's surprising that it does not compile, because the project does not rely on any external dependency.

**Comment by speedingegg** [comment]
suprisingly, it works really well! atleast for a  i7 2600k. thanks for your help!
